[2023-03-31T15:20:08.884+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_Scraping_Dag.save_to_spreadsheet manual__2023-03-31T10:18:49.073005+00:00 [queued]>
[2023-03-31T15:20:08.896+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_Scraping_Dag.save_to_spreadsheet manual__2023-03-31T10:18:49.073005+00:00 [queued]>
[2023-03-31T15:20:08.896+0500] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T15:20:08.897+0500] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T15:20:08.898+0500] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T15:20:08.914+0500] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): save_to_spreadsheet> on 2023-03-31 10:18:49.073005+00:00
[2023-03-31T15:20:08.948+0500] {standard_task_runner.py:55} INFO - Started process 1420 to run task
[2023-03-31T15:20:08.957+0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_Scraping_Dag', 'save_to_spreadsheet', 'manual__2023-03-31T10:18:49.073005+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/AirFlow_Task.py', '--cfg-path', '/tmp/tmp1bwf7tzl']
[2023-03-31T15:20:08.959+0500] {standard_task_runner.py:83} INFO - Job 64: Subtask save_to_spreadsheet
[2023-03-31T15:20:09.064+0500] {task_command.py:388} INFO - Running <TaskInstance: my_Scraping_Dag.save_to_spreadsheet manual__2023-03-31T10:18:49.073005+00:00 [running]> on host Jamshaid-PC.localdomain
[2023-03-31T15:20:09.138+0500] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jamshaid.afzal@tmcltd.com
AIRFLOW_CTX_DAG_OWNER=jamshaid
AIRFLOW_CTX_DAG_ID=my_Scraping_Dag
AIRFLOW_CTX_TASK_ID=save_to_spreadsheet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T10:18:49.073005+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T10:18:49.073005+00:00
[2023-03-31T15:20:09.141+0500] {logging_mixin.py:137} INFO - /home/jamshaid
[2023-03-31T15:20:27.038+0500] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/dags/AirFlow_Task.py", line 52, in save_to_spreadsheet
    sh.append_row(row)
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/worksheet.py", line 1577, in append_row
    return self.append_rows(
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/worksheet.py", line 1627, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/spreadsheet.py", line 150, in values_append
    r = self.client.request("post", url, params=params, json=body)
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/client.py", line 92, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 429, 'message': "Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:1042879034829'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/1042879034829', 'quota_location': 'global', 'quota_limit': 'WriteRequestsPerMinutePerUser', 'service': 'sheets.googleapis.com', 'quota_metric': 'sheets.googleapis.com/write_requests', 'quota_limit_value': '60'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}
[2023-03-31T15:20:27.111+0500] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=my_Scraping_Dag, task_id=save_to_spreadsheet, execution_date=20230331T101849, start_date=20230331T102008, end_date=20230331T102027
[2023-03-31T15:20:27.125+0500] {standard_task_runner.py:100} ERROR - Failed to execute job 64 for task save_to_spreadsheet ({'code': 429, 'message': "Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:1042879034829'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/1042879034829', 'quota_location': 'global', 'quota_limit': 'WriteRequestsPerMinutePerUser', 'service': 'sheets.googleapis.com', 'quota_metric': 'sheets.googleapis.com/write_requests', 'quota_limit_value': '60'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quota#requesting_higher_quota'}]}]}; 1420)
[2023-03-31T15:20:27.155+0500] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T15:20:27.178+0500] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
