[2023-03-31T16:30:36.039+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T11:28:26.960967+00:00 [queued]>
[2023-03-31T16:30:36.054+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T11:28:26.960967+00:00 [queued]>
[2023-03-31T16:30:36.054+0500] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T16:30:36.055+0500] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T16:30:36.056+0500] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T16:30:36.084+0500] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): show_data> on 2023-03-31 11:28:26.960967+00:00
[2023-03-31T16:30:36.110+0500] {standard_task_runner.py:55} INFO - Started process 2753 to run task
[2023-03-31T16:30:36.122+0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_Scraping_Dag', 'show_data', 'manual__2023-03-31T11:28:26.960967+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/AirFlow_Task.py', '--cfg-path', '/tmp/tmpr6y_vwj3']
[2023-03-31T16:30:36.125+0500] {standard_task_runner.py:83} INFO - Job 73: Subtask show_data
[2023-03-31T16:30:36.353+0500] {task_command.py:388} INFO - Running <TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T11:28:26.960967+00:00 [running]> on host Jamshaid-PC.localdomain
[2023-03-31T16:30:36.538+0500] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jamshaid.afzal@tmcltd.com
AIRFLOW_CTX_DAG_OWNER=jamshaid
AIRFLOW_CTX_DAG_ID=my_Scraping_Dag
AIRFLOW_CTX_TASK_ID=show_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T11:28:26.960967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T11:28:26.960967+00:00
[2023-03-31T16:30:38.402+0500] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/client.py", line 150, in open
    properties = finditem(
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/utils.py", line 133, in finditem
    return next(item for item in seq if func(item))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/dags/AirFlow_Task.py", line 57, in show_data
    sh = gc.open('BathBombScraper').sheet1
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/client.py", line 160, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound
[2023-03-31T16:30:38.419+0500] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=my_Scraping_Dag, task_id=show_data, execution_date=20230331T112826, start_date=20230331T113036, end_date=20230331T113038
[2023-03-31T16:30:38.441+0500] {standard_task_runner.py:100} ERROR - Failed to execute job 73 for task show_data (; 2753)
[2023-03-31T16:30:38.470+0500] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T16:30:38.526+0500] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
